### ISSUE TITLE
Support for scala 2.13 and spark 3.2

### ISSUE THREAD

**Issue by vitalvi** [MrPowers/spark-fast-tests#102]
Currently there is no 2.13 version of this package. Could you deploy it's support?

**Comment by MrPowers** [comment]
@vitalvi - I did a Scala 2.13 release, [see here](https://repo1.maven.org/maven2/com/github/mrpowers/spark-fast-tests_2.13/).  Let me know if that works.  cc: @pbarsauskas

**Comment by vitalvi** [comment]
> @vitalvi - I did a Scala 2.13 release, [see here](https://repo1.maven.org/maven2/com/github/mrpowers/spark-fast-tests_2.13/). Let me know if that works. cc: @pbarsauskas

yep, it works perfectly. Thanks a lot @MrPowers
