### ISSUE TITLE
Understanding how to browse/find releases

### ISSUE THREAD

**Issue by nchammas** [MrPowers/spark-fast-tests#107]
Basic question, but I'm a bit confused as to how to find or browse through releases of spark-fast-tests.

* The [GitHub releases](https://github.com/MrPowers/spark-fast-tests/releases) page goes up to v1.0.0.
* A [recent commit](https://github.com/MrPowers/spark-fast-tests/commit/3aa57ae0530fd9c727e20ed406c4be3aff5a1698) mentions v1.2.0, however.
* This [Maven repository](https://mvnrepository.com/artifact/MrPowers/spark-fast-tests?repo=spark-packages) seems to max out at v0.21.1.

Where can I find an authoritative list of spark-fast-test releases, and what is the latest release?

**Comment by nchammas** [comment]
Oh, I think I found it in [this comment](https://github.com/MrPowers/spark-fast-tests/pull/106#issuecomment-1086024774):

https://repo1.maven.org/maven2/com/github/mrpowers/

Is that correct? It looks like latest release is indeed 1.2.0.

If so, feel free to close this issue. 😄

**Comment by MrPowers** [comment]
@nchammas - thanks for creating this issue.

The links for the different JAR files by Scala version are in [this section of the README](https://github.com/MrPowers/spark-fast-tests#install).  Feel free to send a pull request with a clearer description / README layout.

Publishing this library has been an absolute nightmare.  You can see the pain and suffering as the dead bodies of artifacts floating randomly around Maven 😆

**Comment by nchammas** [comment]
README's clear enough! My bad for not reading through it before posting this issue. 😅
