### ISSUE TITLE
Build a Spark 2.3 JAR file

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/spark-fast-tests#14]

**Comment by utdemir** [comment]
`2.2.1` one is also missing from Maven Central.

**Comment by MrPowers** [comment]
@utdemir - I added [a section to the README](https://github.com/MrPowers/spark-fast-tests/#setup) that shows the compatibility matrix between spark-fast-tests and different Spark versions.  All of the recent spark-fast-tests versions should work with Spark 2.2.1.
