### ISSUE TITLE
Add a assertSmallDatasetEquality method

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/spark-fast-tests#2]
There is an `assertDataFrameEquality` method and we need to add an `assertSmallDatasetEquality` for Dataset comparisons.

@snithish found a temporary work-around [here](https://github.com/MrPowers/spark-spec/blob/master/src/test/scala/com/github/mrpowers/spark/spec/sql/DatasetSpec.scala#L1138).  

It'll be good to get a longer term solution.

**Comment by snithish** [comment]
@MrPowers #3 does feel like a good long term fix.

**Comment by MrPowers** [comment]
#6 has been merged with master!!  Now `assertSmallDatasetEquality` will work for both DataFrames and Datasets.  I'm really excited about this!
