### ISSUE TITLE
Issue with schemas and assertSmallDataFrameEquality

### ISSUE THREAD

**Issue by khampson** [MrPowers/spark-fast-tests#20]
Hi:

I was following your [Testing Spark Applications](https://medium.com/@mrpowers/testing-spark-applications-8c590d3215fa) Medium article, and ran into an issue relating to schemas and spark-fast-tests' `assertSmallDataFrameEquality` method.

I created the source DataFrame using `toDF` as suggested, and the expected `DataFrame` using an explicitly defined schema using a `List` of `StructField`s as suggested. The issue I ran into was that, since `toDF` always has the field being `nullable`, and in my case the expected `DataFrame`s were not `nullable`, the [schema comparison](https://github.com/MrPowers/spark-fast-tests/blob/fd0c338b1eee4ab777ebe7bf6ca6dcd7810acbe7/src/main/scala/com/github/mrpowers/spark/fast/tests/DatasetComparer.scala#L54) would always fail for that reason.

Perhaps there could be an option to ignore the nullability when doing the compare, such that as long as the names and types are the same it's a match?

Thanks,
Ken

**Comment by MrPowers** [comment]
@khampson - I suggest using the `createDF` method [outlined in this blog post](https://medium.com/@mrpowers/manually-creating-spark-dataframes-b14dae906393) to avoid the `nullable` issue.  The `createDF` method is defined in [spark-daria](https://github.com/MrPowers/spark-daria).

That being said, I think you're right that the `assertSmallDataFrameEquality` method should have a `ignoreNullable` flag when users don't want to factor in the `nullable` property in their equality comparison.  I'll look into this.

**Comment by khampson** [comment]
@MrPowers : Thanks! I'll try the `createDF` approach for now.

Thanks for looking into the `ignoreNullable` flag as well! I think that's ultimately the method I would prefer to use for my particular case (and probably for my "general case"), as if there was a discrepancy involving a null value, I imagine that would generally come to light as a discrepancy between actual and expected values for that field.

**Comment by MrPowers** [comment]
@khampson - I added the `ignoreNullable` option to the `assertSmallDataFrameEquality` method in this commit: https://github.com/MrPowers/spark-fast-tests/commit/178bbb154ed69e0da019b425811ee28a3c75599b

I'll send you another message when I do a release and an updated JAR file is accessible via JitPack.

**Comment by khampson** [comment]
@MrPowers : Thanks!

**Comment by MrPowers** [comment]
@khampson - I forgot to follow up with you on this issue, but the JAR files with `ignoreNullable` are available (and have been for a while).  Let me know how it's working for you!
