### ISSUE TITLE
Repurposing DataFrameComparer to compare Dataset

### ISSUE THREAD

**Issue by snithish** [MrPowers/spark-fast-tests#3]
@MrPowers I was wondering if we can repurpose DataframeComparer to compare Datasets too, since Dataframe is nothing but `Dataset[Row]` we can use Generics to use the same trait for Dataset.

I think

`def assertSmallDataFrameEquality[T](actualDS: Dataset[T], expectedDS: Dataset[T])`

`def assertLargeDataFrameEquality[T](actualDS: Dataset[T], expectedDS: Dataset[T])` 

can be used with the exact same logic used now. Making these functions Generic will make them versatile. Type inference will make invocation simple without the need to specify Type information.

Let me know what you think about this.

**Comment by MrPowers** [comment]
@snithish - Yea, your suggestion sounds awesome!

Can you please submit a pull request?  Thanks!

**Comment by snithish** [comment]
@MrPowers I am working on it, will raise one by the end of the week.

**Comment by MrPowers** [comment]
@snithish - Awesome, thanks for the help.  Feel free to ping me anytime if you need anything!

**Comment by snithish** [comment]
@MrPowers what is the reason behind having `assertSmallDataFrameEquality` and `assertLargeDataFrameEquality`. I am thinking we could have a single assertEquality method which will look at schema mismatch, count mismatch and prints out only unequal rows in both datasets. 

Error format would be Row ("Alice", 12) not present in expectedDF.

Thoughts?

**Comment by MrPowers** [comment]
@snithish - Sorry for the delayed response.

`assertSmallDataFrameEquality` is significantly faster than `assertLargeDataFrameEquality`.  `assertLargeDataFrameEquality` uses the same approach as `assertDataFrameEquals` in [spark-testing-base](https://github.com/holdenk/spark-testing-base).

The spark-spec test suite ran about 50% faster when I replaced `assertDataFrameEquals` with `assertSmallDataFrameEquality`.

`assertSmallDataFrameEquality` calls `collect`, so it can only be used for DataFrames that are small enough to fit on the driver node.  `assertLargeDataFrameEquality` needs to be used to compare DataFrames that are partitioned across several nodes.

Let me know what you think.

**Comment by snithish** [comment]
@MrPowers Totally agree performance considerations and driver node issue. #4 would be really good.
Wondering if we could have a `assertEquals[U](expected: Dataset[U], result: Dataset[U])` which would indirectly call `assertSmallDataFrameEquality` and `assertLargeDataFrameEquality` depending on the size of dataset.

**Comment by MrPowers** [comment]
@snithish - I am working on #6 to move from `assertSmallDataFrameEquality` to `assertSmallDatasetEquality`.  `assertSmallDatasetEquality` will be able to take either DataFrames or Datasets as arguments.

I really like your idea of having "`assertEquals[U](expected: Dataset[U], result: Dataset[U])` which would indirectly call `assertSmallDataFrameEquality` and `assertLargeDataFrameEquality` depending on the size of dataset".  I am going to brainstorm a generic `assertEquals` once the  `assertSmallDatasetEquality` stuff is merged with master.

Thanks for the awesome ideas!!!
