### ISSUE TITLE
Allow ErrorMessage formatting for scalatest users

### ISSUE THREAD

**Issue by rdefreitas** [MrPowers/spark-fast-tests#39]
First off, fantastic library.

Secondly, I've incorporated spark-fast-tests into a project that was already using scalatest and maven, but when I run a failing test I get lines like so:

```
##teamcity[testFailed name='Derives a correct 14-digit Completion Api' message='|n[01-001-00000-00-00|] || [01-001-00000-00-01|]|n[02-001-00000-00-01|] || [02-001-00000-00-02|]|n[03-001-00000-00-02|] || [03-001-00000-00-03|]|n[04-001-00000-00-03|] || [04-001-00000-00-04|]|n[05-001-00000-00-04|] || [05-001-00000-00-05|]|n[06-001-00000-00-05|] || [06-001-00000-00-01|]' details='com.github.mrpowers.spark.fast.tests.DatasetContentMismatch: |n[01-001-00000-00-00|] || [01-001-00000-00-01|]|n[02-001-00000-00-01|] || [02-001-00000-00-02|]|n[03-001-00000-00-02|] || [03-001-00000-00-03|]|n[04-001-00000-00-03|] || [04-001-00000-00-04|]|n[05-001-00000-00-04|] || [05-001-00000-00-05|]|n[06-001-00000-00-05|] || [06-001-00000-00-01|]|r|n	at com.github.mrpowers.spark.fast.tests.DatasetComparer$class.assertSmallDatasetEquality(DatasetComparer.scala:70)|r|n	at com.rseg.spark.test.etl.WellApiHelperSpec.assertSmallDatasetEquality(WellApiHelperSpec.scala:15)|r|n	at com.github.mrpowers.spark.fast.tests.DataFrameComparer$class.assertSmallDataFrameEquality(DataFrameComparer.scala:16)|r|n	at com.rseg.spark.test.etl.WellApiHelperSpec.assertSmallDataFrameEquality(WellApiHelperSpec.scala:15)|r|n	at com.rseg.spark.te...
```

Is there a way to change the formatting to print like other scalatest messages?

**Comment by snithish** [comment]
@rdefreitas I believe your `CI teamcity` removes the formatting when displaying the error message. When run in IntelliJ and a terminal the formatting is preserved. 

<img width="968" alt="ErrorWithProperFormatting" src="https://user-images.githubusercontent.com/7392212/47229317-bd23e900-d3c7-11e8-8fac-982e4f875658.png">

Can you help out with a sample error message `teamcity` shows properly formatted?

**Comment by MrPowers** [comment]
Thanks for opening this issue @rdefreitas 😄 

@snithish and I would love to replicate this bug, so we can figure out how to fix it!  Feel free to open up a pull request in the [spark-spec](https://github.com/MrPowers/spark-spec) project that illustrates the bug!

I mainly use spark-fast-tests with [utest](https://www.mungingdata.com/apache-spark/testing-with-utest), but am determined to make spark-fast-tests awesome for scalatest users too.  Your feedback is welcome and appreciated!

**Comment by awhillas** [comment]
Just to add to this issue, its _very_ difficult to read schema missmatches. This is an example of what I'm getting using `sbt test`
```
[info] - cumulativeByMonth *** FAILED *** (250 milliseconds)
[info]   com.github.mrpowers.spark.fast.tests.DatasetSchemaMismatch: Actual Schema:
[info] StructType(StructField(month,DateType,false), StructField(pressroom_id,IntegerType,false), StructField(total_content,IntegerType,false), StructField(number_of_views,IntegerType,false), StructField(total_time_on_page,IntegerType,false), StructField(avg_time_on_page,DoubleType,false), StructField(opens,IntegerType,false), StructField(clicks,IntegerType,false), StructField(delivereds,IntegerType,false), StructField(open_rate,DoubleType,true), StructField(click_rate,DoubleType,true), StructField(total_content_std,DoubleType,true), StructField(total_content_avg,DoubleType,true), StructField(avg_time_on_page_std,DoubleType,true), StructField(avg_time_on_page_avg,DoubleType,true), StructField(open_rate_std,DoubleType,true), StructField(open_rate_avg,DoubleType,true), StructField(click_rate_std,DoubleType,true), StructField(click_rate_avg,DoubleType,true), StructField(total_content_z,DoubleType,true), StructField(time_on_page_z,DoubleType,true), StructField(open_rate_z,DoubleType,true), StructField(click_rate_z,DoubleType,true))
[info] Expected Schema:
[info] StructType(StructField(pressroom_id,IntegerType,false), StructField(month,DateType,false), StructField(total_content,IntegerType,false), StructField(number_of_views,IntegerType,false), StructField(total_time_on_page,IntegerType,false), StructField(avg_time_on_page,DoubleType,false), StructField(contacts,IntegerType,false), StructField(followers,IntegerType,false), StructField(opens,IntegerType,false), StructField(clicks,IntegerType,false), StructField(delivereds,IntegerType,false))
```
having them in columns with the offenders in red (or another colour) would be very helpful.

Also, i'm getting the similar problems to @rdefreitas, but just the first example is on the same line as the message.

Thanks again for the great lib!

**Comment by rdefreitas** [comment]
I''m actually not running teamcity at all, which is part of the problem here... the error messages were all coming up, even in intellij, as being prefixed with ##teamcity

**Comment by MrPowers** [comment]
Error messages should be better in the newer versions of this lib.  Feel free to open this back up / open up a new issue if you're still having issues with the error messages.  Thanks!
