### ISSUE TITLE
Support for Scala 2.12

### ISSUE THREAD

**Issue by oscarvarto** [MrPowers/spark-fast-tests#41]
Hi @MrPowers !

Today I started my journey with Apache Spark, once I learned that Spark 2.4.0 can be run with Scala 2.12.
So, I forked your https://github.com/MrPowers/spark-sbt.g8 giter8 template, tweaked it somewhat to work with current stable Scala version,
and then I got a run-time error.

My hunch is that the release of spark-fast-tests I am using, is for Scala 2.11.X only, and might not be binary compatible with next Scala 2.12.X libraries (ScalaTest?).

The error I am getting is this:

```text
[info] MannersSpec:
[info] com.intersysconsulting.TubularSpec *** ABORTED *** (28 milliseconds)
[info]   java.lang.NoSuchMethodError: com.github.mrpowers.spark.fast.tests.DatasetComparer.$init$(Lcom/github/mrpowers/spark/fast/tests/DatasetComparer;)V
[info]   at com.intersysconsulting.TubularSpec.<init>(TubularSpec.scala:11)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]   at java.lang.Class.newInstance(Class.java:442)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:435)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   ...
[info] com.intersysconsulting.MannersSpec *** ABORTED *** (4 milliseconds)
[info]   java.lang.NoSuchMethodError: com.github.mrpowers.spark.fast.tests.DatasetComparer.$init$(Lcom/github/mrpowers/spark/fast/tests/DatasetComparer;)V
[info]   at com.intersysconsulting.MannersSpec.<init>(MannersSpec.scala:10)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]   at java.lang.Class.newInstance(Class.java:442)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:435)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   ...
[error] Uncaught exception when running com.intersysconsulting.MannersSpec: java.lang.NoSuchMethodError: com.github.mrpowers.spark.fast.tests.DatasetComparer.$init$(Lcom/github/mrpowers/spark/fast/tests/DatasetComparer;)V
[error] sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: com.github.mrpowers.spark.fast.tests.DatasetComparer.$init$(Lcom/github/mrpowers/spark/fast/tests/DatasetComparer;)V
[error] 	at com.intersysconsulting.MannersSpec.<init>(MannersSpec.scala:10)
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error] 	at java.lang.Class.newInstance(Class.java:442)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:435)
[error] 	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

My complete source code, so that you can reproduce the error above is here: https://github.com/oscarvarto/learning-spark/
I am depending on a SBT-1.X compatible plugin, as shown here: https://github.com/oscarvarto/learning-spark/blob/master/project/plugins.sbt#L3-L4

**Comment by oscarvarto** [comment]
I started reviewing what are the dependencies for spark-fast-tests, to see if I could make a pull request.
However, I just noticed there is a circular dependency with spark-daria. So I don't know how to proceed.

First hunch is:

1. Try to get spark-daria cross compiling for Scala versions 2.11.12 and 2.12.7, simply ignoring those tests that require have a dependency on spark-fast-tests. Publish-local the binary.
2. Then try to use the local spark-daria binaries work for this repo.
3. Make PRs to both repos.

But I'm not sure if it is a good practice to have circular dependencies this way in the first place.

What do you think @MrPowers ?

**Comment by MrPowers** [comment]
@oscarvarto - thanks for opening this issue & for the PRs.

I am going to start by removing the spark-daria dependency from spark-fast-tests, so we can circumvent the circular dependency issue entirely.

We can then work on getting spark-fast-tests built with Scala 2.12.  After that's done, we can focus on getting spark-daria built with Scala 2.12.  I'm looking forward to collaborating with you on this!

cc: @snithish

**Comment by snithish** [comment]
> @oscarvarto - thanks for opening this issue & for the PRs.
> 
> I am going to start by removing the spark-daria dependency from spark-fast-tests, so we can circumvent the circular dependency issue entirely.
> 
> We can then work on getting spark-fast-tests built with Scala 2.12. After that's done, we can focus on getting spark-daria built with Scala 2.12. I'm looking forward to collaborating with you on this!
> 
> cc: @snithish

This is interesting, I will have a look too, when I find some free time

**Comment by MrPowers** [comment]
@oscarvarto - FYI, I eliminated the spark-daria dependency: https://github.com/MrPowers/spark-fast-tests/commit/60f49f5ce714d7e1eae767507333fe575d92b284

**Comment by MrPowers** [comment]
Scala 2.12 support has been added.  Thanks for all the help everyone.
