### ISSUE TITLE
assertApproximateDataFrameEquality with ignoreNullable and orderedComparison flags

### ISSUE THREAD

**Issue by ggalves** [MrPowers/spark-fast-tests#49]
The problem: I am comparing two dataframes with a DoubleType field, and this comparision needs to be approximate. But I'm having problems with schema because of nullable fields.

This flags would be very useful for my case. Is this possible?

**Comment by MrPowers** [comment]
@ggalves - Sure, I added the `ignoreNullable` feature in this commit: https://github.com/MrPowers/spark-fast-tests/commit/3ea8d89d15bcee8452249f9e059b824caf658948

I will try to get on the `orderedComparison` feature soon.  Little too sleepy to do it right now.

**Comment by MrPowers** [comment]
@ggalves - Have you looked at the `assertDoubleTypeColumnEquality` method?  That might help you solve your problem too as that method doesn't look at the nullable property or the column name.  Only downside is that it can only compare two columns, not two entire DataFrames.

**Comment by ggalves** [comment]
Thank you for the feature!

About `assertDoubleTypeColumnEquality`, i haven't looked yet, may be interesting for my case. I'm taking a look at this today. Thanks again!

**Comment by MrPowers** [comment]
@ggalves - I updated the `assertApproximateDataFrameEquality` method to optionally take the `ignoreNullable` and `orderedComparison` flags.  The new code has been released in v0.19.1.  Let me know how this code works for you!

**Comment by ggalves** [comment]
@MrPowers thank you! But have you released v0.19.1? I couldn't find it

**Comment by MrPowers** [comment]
@ggalves - I'm grabbing it from Maven ([example here](https://github.com/MrPowers/spark-daria/commit/8e28aef7be7b7c5eb209c5454290d50c5979c53c)), but you're right, I forgot to do a release.

Here's the release link: https://github.com/MrPowers/spark-fast-tests/releases/tag/v0.19.1

Let me know if this works for you!

**Comment by MrPowers** [comment]
@ggalves - Were you able to find the release OK?  Can I close this issue?

**Comment by ggalves** [comment]
Hey, I'm sorry, I couldn't test it yet. I'm testing it tomorrow.

**Comment by ggalves** [comment]
@MrPowers I tested it just now. `ignoreNullable` is working, but I couldn't find `orderedComparison` flag in `assertApproximateDataFrameEquality`

**Comment by MrPowers** [comment]
@ggalves - Think I finally fixed this: https://github.com/MrPowers/spark-fast-tests/commit/28351e772a48e7968b6e90e674d1fb2b2853844f

Sorry for keeping on messing this one up.  See version 0.19.2.

Let me know if there is anything else you need.

**Comment by ggalves** [comment]
@MrPowers This commit is what I need, thank you! Can you release 0.19.2, please?
