### ISSUE TITLE
Managing the Spark Session

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/spark-fast-tests#5]
In the [spark-fast-tests README](https://github.com/MrPowers/spark-fast-tests#usage), we encourage users to wrap the Spark Session in a trait and mix in the trait to test classes that need access to the Spark Session.

```scala
import org.apache.spark.sql.SparkSession

trait SparkSessionTestWrapper {

  lazy val spark: SparkSession = {
    SparkSession.builder().master("local").appName("spark session").getOrCreate()
  }

}
```

The spark-testing-base library uses the [EvilSessionTools approach](https://github.com/holdenk/spark-testing-base/blob/38cada03f9c34aafea97210957dd32718628f0d7/src/main/2.0/scala/org/apache/spark/sql/EvilSessionTools.scala) to [extract the SQL context](https://github.com/holdenk/spark-testing-base/blob/7191b78ce8160f5dc9e44a3a5751f771bac66848/src/main/2.0/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala#L235).

I don't think the testing framework should have any knowledge or control over the Spark Session.  The Spark Session management should take place in the application and the test framework should simply provide tools that help with assertions.

@snithish @eclosson - I would like your feedback on this intentional design decision.  Thanks!

**Comment by eclosson** [comment]
> I don't think the testing framework should have any knowledge or control over the Spark Session. The Spark Session management should take place in the application and the test framework should simply provide tools that help with assertions.

I think this is a sound approach. If there is a strong need for helpers that make creating and accessing a spark session easier probably better to include that in a different library.

**Comment by snithish** [comment]
Abstracting out Spark Session from testing framework is a good thought. It's Dependency Injection done right.

**Comment by MrPowers** [comment]
@eclosson @snithish - Thanks for the feedback.  I'm going to open an issue in the spark-testing-base library and see if they would consider removing the SparkSession management from DataFrameSuiteBase.  I'd like the good ideas we develop in this testing framework to get reflected in the spark-testing-base repo as well since it's more popular.

**Comment by MrPowers** [comment]
@eclosson @snithish - I created an issue in the spark-testing-base repo: https://github.com/holdenk/spark-testing-base/issues/186  Feel free to chime in on the issue if you'd like to add anything.

**Comment by MrPowers** [comment]
I'm confident that we're managing the Spark Session correctly in this package.  I'll try to submit a pull request to spark-testing-base soon to separate out the Spark Session from DataFrame suite base.  Thanks for the feedback.
