### ISSUE TITLE
Publish to Maven Central?

### ISSUE THREAD

**Issue by netvl** [MrPowers/spark-fast-tests#50]
I noticed that this library (which is awesome BTW!) was being published to Maven Central some time ago, but then stopped: https://search.maven.org/classic/#search|ga|1|spark-fast-tests (last release is in June 2018). Is it possible to publish newer versions to Maven Central again?

The issue is, using third-party repositories is often very hard in certain companies which only allow using a proxying artifacts repository which is configured to work with Maven Central and almost nothing else, and are very reluctant to add any other repository to proxy. Thus, there is really no way to use your library, because even if it works on the dev machines, it won't work on CI which is only allowed to use the internal repository.

**Comment by MrPowers** [comment]
@netvl - Thanks for opening this issue.

I am bad with Maven and fought a losing battle last year.  Those libraries at [your link](https://search.maven.org/classic/#search|ga|1|spark-fast-tests) are actually malformed.

I tried to figure this out last year ([see here for details](https://stackoverflow.com/questions/50893846/maven-jar-file-only-includes-html-files-not-scala-classes)) and failed.  

From what I can tell, you're aware that the spark-fast-tests JAR files are [here](https://mvnrepository.com/artifact/MrPowers/spark-fast-tests?repo=spark-packages).  Can you please confirm that "MVN Repository" is one of the "proxying artifact repositories" you're referring to?

I will be at the Spark Summit next week and will ask around and see if anyone can help me figure out how to get the JAR files on Maven Central.  Let me know if you've done this before and would be willing to submit a PR.  I'm definitely willing to do whatever it takes to solve this issue - thanks again for letting me know about this!

**Comment by netvl** [comment]
> From what I can tell, you're aware that the spark-fast-tests JAR files are here. Can you please confirm that "MVN Repository" is one of the "proxying artifact repositories" you're referring to?

The mvnrepository.com site is not a proper artifacts storage, from what I understand - it is just an aggregator of information about artifacts stored in different maven repositories. For example, specifically for this library it shows that it is available in a particular bintray repository:
![image](https://user-images.githubusercontent.com/280456/56328354-6f4c2b80-6133-11e9-9282-ba3f18098834.png)

Under "proxying artifact repositories" I meant something like Sonatype Nexus or JFrog Artifactory, which can be set up to proxy "outside world" repositories, so the users would configure to pull artifacts from some internal Nexus/Artifactory host, and this system will go and fetch the requested artifact from one of the public repositories, in most cases caching it locally afterwards. These systems have to be configured with a list of public repositories to connect to, and in many companies for various reasons this list is more or less fixed and could be hard (in the organizational sense) to modify; Maven Central, however, is proxied in almost 100% of use cases, from my experience.

>  Let me know if you've done this before and would be willing to submit a PR. I'm definitely willing to do whatever it takes to solve this issue - thanks again for letting me know about this!

Yes, I've done this before, for example, in this library: https://github.com/netvl/picopickle (even though I stopped supporting it some time ago, I think that the publishing process has not changed since them). The process is not without bumps, compared to publishing e.g. to Cargo or NPM, but it is doable - moreover, it is made much easier if you do publishing to Maven Central through Bintray. There is a number of articles on the internet on how to do it, for example: https://reflectoring.io/bintray-jcenter-maven-central/. That's what I used for the aforementioned library, and it was pretty simple - just set up a custom Bintray repository, ask to include it to the JCenter repository and to enable Maven Central synchronization, and then a few lines to configure the bintray plugin in the SBT build. From what I understand, you already went through the hardest part of requesting a group id in Sonatype repositories, so some bits of configuration on Bintray side are more or less all what you would need to do.

As for submitting a PR, I would really much like to do it, but I'm not sure when I'll be able to actually do it :(

**Comment by MrPowers** [comment]
@netvl - thanks for the detailed response.  I will try to figure this out and will keep you posted!

**Comment by marcostong17** [comment]
hi @MrPowers any luck with updating the artifacts to maven central? the artifacts available in there dont have the .class files for spark-fast-tests.

**Comment by MrPowers** [comment]
@netvl @marcostong17 - The artifacts have been published to Maven and can be accessed by adding this line to the `build.sbt` file:

```scala
libraryDependencies += "com.github.mrpowers" %% "spark-fast-tests" % "0.21.3" % "test"
```

Sorry it took so long and thanks for commenting.
