### ISSUE TITLE
Data Volume grown when ran Compaction API

### ISSUE THREAD

**Issue by sanjiv1980** [MrPowers/spark-fast-tests#61]
Hi Matt,

I have gone through your article that you have written(and youtube) , I wanted to say like they are just wonderful.Thank you very much for that.!!!

I have one question , which I observed and put across delta lake community as well .

I found like while doing compaction operation, data volume is growing like anything . I could not able to understand the reason behind it. Could you please help me to understand .

here is the test case that I have performed .

Here is the details:

Took Sample of 166MB of input data. : Total number Records : 1630168
Once Delta Lake formed It became of 176MB : Total number of Records : 1630168
Ran merge API to update id , now size became 221MB
Ran Vacuum API, now size became 205MB : Total number of records : 1630168
Ran Compaction Now size became 781MB : Total number of records : 3260336 (double of original)
Ran Vacuum API now size became 576MB : Total number of records : 1630168

My code is also attached over here : https://github.com/delta-io/delta/issues/254

**Comment by MrPowers** [comment]
Looks like this conversation took place on the Delta issue, thanks!
