### ISSUE TITLE
java.lang.NoSuchMethodError: com.github.mrpowers.spark.fast.tests.DatasetComparer.$init$

### ISSUE THREAD

**Issue by kantjessica** [MrPowers/spark-fast-tests#65]
Hi Guys,

I am about to use this nice framework in our tests (combined with scalatest). By simply copy-paste the sample code from your page. We have gotten the error as described in the title.

scalaVersion: 2.12.7
sparkVersion: 2.4.2
scalatestVersion: 3.1.1
spark-fast-testsVersion: 0.19.1

```scala
class Test extends AnyFlatSpec with DataFrameComparer {

  "a" should "b" in {
    print("works")
  }

}
```

Can you guys help me out?

**Comment by MrPowers** [comment]
Thanks for creating this issue.

My guess is that you're using the spark-fast-tests version that's for Scala 2.11.  Try this:

```scala
libraryDependencies += "MrPowers" % "spark-fast-tests" % "0.20.0-s_2.12" % "test"
```

I was able to get `AnyFlatSpec` working with `DataFrameComparer` - see [this commit](https://github.com/MrPowers/scalatest-example/commit/ec28234bb180ed881492fb3ce11b02e80c9c60fb). 

Here's the code:

```scala
package com.github.mrpowers.scalatest.example

import com.github.mrpowers.spark.fast.tests.DataFrameComparer
import org.scalatest.flatspec.AnyFlatSpec

class AnyFlatExampleSpec
    extends AnyFlatSpec
    with DataFrameComparer
    with SparkSessionTestWrapper {

  import spark.implicits._

  "a" should "b" in {
    println("works")
  }

  it should "have size 0" in {
    assert(Set.empty.size === 0)
  }

  it should "compare two DataFrames" in {
    val df1 = Seq((2), (6), (5)).toDF("num")
    val df2 = Seq((2), (6), (5)).toDF("num")
    assertSmallDataFrameEquality(df1, df2)
  }

}
```

Let me know if this solves your issue!

**Comment by kantjessica** [comment]
Thanks Bro. you save my day!! :-)
