### ISSUE TITLE
After using the library my logging level has changed to INFO

### ISSUE THREAD

**Issue by suchitgupta01** [MrPowers/spark-fast-tests#75]
I was trying the library and found that after including it the logging changed to INFO from DEBUG.

I tried a few things but not working.

plugins.sbt:
`
logLevel := Level.Error
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.10")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.1")
`
spark session:
`
 SparkSession
      .builder
      .appName(appName)
      .master("local[2]")
      //to fix issue of port assignment on local
      .config("spark.driver.bindAddress", "localhost")
      .getOrCreate()
     spark.sparkContext.setLogLevel("ERROR")
`
If I remove the library logging is back to Error.

How can get it fixed with the Library?

**Comment by MrPowers** [comment]
@suchitgupta01 - thanks for opening the issue.

[Here are the logging settings I use](https://github.com/MrPowers/spark-spec/blob/master/src/test/resources/log4j.properties).

Create a `src/test/resources/log4j.properties` file, copy those settings in there, and let me know if that solves you problem 😄

**Comment by suchitgupta01** [comment]
@MrPowers I already have the file but somehow with the library, it is not working.

**Comment by MrPowers** [comment]
Hmmm, not sure, but don't think logging is related to this lib.  Feel free to open this back up if I'm missing something and this lib is somehow messing up the logging stuff.  Thanks!
