### ISSUE TITLE
Spark 3 comparation of strings fail due to a missing method

### ISSUE THREAD

**Issue by alfonsorr** [MrPowers/spark-fast-tests#86]
It looks like spark 3 deleted `dateToString` method in `org.apache.spark.sql.catalyst.util.DateTimeUtils` to prevent the use of SimpleDateFormat (a non thread safe use).

This implementation should have a custom implementation valid for spark 2.X and 3.X

**Comment by MrPowers** [comment]
Merged this & made a release, thank you!
