### ISSUE TITLE
Create a generic assertDatasetEquality method

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/spark-fast-tests#9]
`assertDatasetEquality[U](expected: Dataset[U], result: Dataset[U])` could indirectly call `assertSmallDatasetEquality` and `assertLargeDatasetEquality` depending on the size of dataset.

I'm not really sure of a good way to implement this.  `assertDatasetEquality` would need to run a count, which could be expensive.  The definition of a "large" Dataset would depend on the machine... we would somehow need to compare the Dataset size with the available machine resources.

Any good ideas on how to implement this @snithish?

**Comment by snithish** [comment]
@MrPowers I am stumbled by it too. Guess we could keep this issue open and get more views on it.

**Comment by MrPowers** [comment]
Don't think this is possible.  Closing this for now.
