### ISSUE TITLE
Bintray Sunsetted

### ISSUE THREAD

**Issue by pkoplik24** [MrPowers/spark-fast-tests#94]
Failed to collect dependencies at MrPowers:spark-fast-tests:jar:0.21.1-s_2.11: Failed to read artifact descriptor for MrPowers:spark-fast-tests:jar:0.21.1-s_2.11: Could not transfer artifact MrPowers:spark-fast-tests:pom:0.21.1-s_2.11 from/to spark-fast-tests (https://dl.bintray.com/spark-packages/maven/): Authorization failed for https://dl.bintray.com/spark-packages/maven/MrPowers/spark-fast-tests/0.21.1-s_2.11/spark-fast-tests-0.21.1-s_2.11.pom 403 Forbidden -> [Help 1]

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by MrPowers** [comment]
@pkoplik24 - thanks for reporting this.  JFrog unfortunately did a major disservice to the entire Scala community by shutting down Bintray.  Can you use `libraryDependencies += "com.github.mrpowers" %% "spark-fast-tests" % "0.23.0" % "test"` to fetch the dependency directly from Maven?

**Comment by pkoplik24** [comment]
Perfect, works fine. Thank you!
